<script>
(function(){
  if (window.__lighom_viewcat_setup) return;
    window.__lighom_viewcat_setup = true;
      function ck(name) { var m = document.cookie.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]+)')); return m ? decodeURIComponent(m[1]) : ''; }
        function getVariantIdsFromDOM() {
            var html = document.body.innerHTML;
                var m = html.match(/180689[\d]{18,20}/g);
                    if (!m) return [];
                        return Array.from(new Set(m)).slice(0, 30);
                          }
                            function getIdsFromDL(){ try { var dl=window.dataLayer||[]; for (var i=0;i<dl.length;i++){ var it=dl[i]; if(!it||typeof it!=='object') continue; var isList=(it.event==='view_item_list')||(it['1']==='view_item_list'); if(!isList) continue; var p=it['2']||it; var items=(p.ecommerce&&p.ecommerce.items)||p.items; if(items&&items.length){ var z=items.map(function(x){return String(x.item_id||x.id||x.variant_id||'');}).filter(Boolean); if(z.length) return Array.from(new Set(z)).slice(0,30); } } } catch(e){} return []; }
  function fireMeta(listName) {
                                if (window.__lighom_viewcat_fired) return;
                                    var ids = getVariantIdsFromDOM(); if (!ids.length) ids = getIdsFromDL();
                                        if (!ids.length) return;
                                            window.__lighom_viewcat_fired = true;
                                                try {
                                                      var category = listName || (document.querySelector('h1') ? document.querySelector('h1').textContent.trim() : document.title);
                                                            category = (category || '').slice(0, 80);
                                                                  var eventId = 'viewcat_' + Date.now() + '_' + Math.random().toString(36).substr(2,9);
                                                                        window.dataLayer = window.dataLayer || [];
                                                                              window.dataLayer.push({
                                                                                      event: 'view_category',
                                                                                              event_id: eventId,
                                                                                                      content_category: category,
                                                                                                              content_ids: ids,
                                                                                                                      content_type: 'product_group',
                                                                                                                              currency: 'USD',
                                                                                                                                      fbp: ck('_fbp'), fbc: ck('_fbc'), epik: ck('_epik')
                                                                                                                                            });
                                                                                                                                                  if (window.fbq) {
                                                                                                                                                          window.fbq('track', 'ViewContent', {
                                                                                                                                                                    content_category: category,
                                                                                                                                                                              content_ids: ids,
                                                                                                                                                                                        content_type: 'product_group',
                                                                                                                                                                                                  currency: 'USD',
                                                                                                                                                                                                            eventID: eventId
                                                                                                                                                                                                                    }, { eventID: eventId });
                                                                                                                                                                                                                          }
                                                                                                                                                                                                                              /* Worker fanout — Meta CAPI + Pinterest only (GA4 view_item_list fires from Shopline native gtag). */
                                                                                                                                                                                                                              try {
                                                                                                                                                                                                                                var ud = window.__lighom_user_data_hashed || {};
                                                                                                                                                                                                                                fetch('https://lighom-feed-server.dikecarmem750.workers.dev/capi/event', {
                                                                                                                                                                                                                                  method: 'POST', credentials: 'omit', keepalive: true,
                                                                                                                                                                                                                                  headers: {'Content-Type':'application/json'},
                                                                                                                                                                                                                                  body: JSON.stringify({
                                                                                                                                                                                                                                    event_name: 'ViewCategory', event_id: eventId,
                                                                                                                                                                                                                                    event_time: Math.floor(Date.now()/1000),
                                                                                                                                                                                                                                    page_url: location.href, page_path: location.pathname,
                                                                                                                                                                                                                                    page_type: 'category',
                                                                                                                                                                                                                                    fanout: ['meta', 'pinterest'],
                                                                                                                                                                                                                                    user_data: Object.assign({}, ud, {
                                                                                                                                                                                                                                      fbc: ck('_fbc'), fbp: ck('_fbp'), epik: ck('_epik'),
                                                                                                                                                                                                                                      ga_cookie: ck('_ga'), client_ua: navigator.userAgent
                                                                                                                                                                                                                                    }),
                                                                                                                                                                                                                                    custom_data: {
                                                                                                                                                                                                                                      content_category: category,
                                                                                                                                                                                                                                      content_ids: ids,
                                                                                                                                                                                                                                      content_type: 'product_group',
                                                                                                                                                                                                                                      currency: 'USD'
                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                    utm: {
                                                                                                                                                                                                                                      source: ck('last_utm_source') || ck('first_utm_source') || '',
                                                                                                                                                                                                                                      medium: ck('last_utm_medium') || ck('first_utm_medium') || '',
                                                                                                                                                                                                                                      campaign: ck('last_utm_campaign') || ck('first_utm_campaign') || ''
                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                  })
                                                                                                                                                                                                                                }).catch(function(){});
                                                                                                                                                                                                                              } catch(e){}
                                                                                                                                                                                                                              } catch(e) {}
                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                  function getListNameFromDL() {
                                                                                                                                                                                                                                      var dl = window.dataLayer || [];
                                                                                                                                                                                                                                          for (var i = 0; i < dl.length; i++) {
                                                                                                                                                                                                                                                var it = dl[i];
                                                                                                                                                                                                                                                      if (!it || typeof it !== 'object') continue;
                                                                                                                                                                                                                                                            var isList = (it.event === 'view_item_list') || (it['1'] === 'view_item_list');
                                                                                                                                                                                                                                                                  if (!isList) continue;
                                                                                                                                                                                                                                                                        var p = it['2'] || it;
                                                                                                                                                                                                                                                                              var items = (p.ecommerce && p.ecommerce.items) || p.items;
                                                                                                                                                                                                                                                                                    if (items && items[0] && items[0].item_list_name) return items[0].item_list_name;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                            return null;
                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                function tryFire() { fireMeta(getListNameFromDL()); }
                                                                                                                                                                                                                                                                                                  if (document.readyState === 'loading') {
                                                                                                                                                                                                                                                                                                      document.addEventListener('DOMContentLoaded', tryFire);
                                                                                                                                                                                                                                                                                                        } else {
                                                                                                                                                                                                                                                                                                            tryFire();
                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                setTimeout(tryFire, 500);
                                                                                                                                                                                                                                                                                                                  setTimeout(tryFire, 1500);
                                                                                                                                                                                                                                                                                                                    setTimeout(tryFire, 3000);
                                                                                                                                                                                                                                                                                                                    })();
                                                                                                                                                                                                                                                                                                                    </script>