"""Google Product Category mapping for Lighom customCat values."""
from __future__ import annotations


GPC_MAP = {
    'Lighting > Ceiling lights > Pendant lighting': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Ceiling lights > Chandeliers': ('Home & Garden > Lighting > Light Fixtures > Chandeliers', 3247),
    'Lighting > Ceiling lights > Flush mount lighting': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Ceiling lights > Semi-flush mount light': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Ceiling lights > Ceiling Fans': ('Home & Garden > Household Appliances > Climate Control Appliances > Air Conditioners > Ceiling Fans', 2806),
    'Lighting > Wall Lights > Wall sconces': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Wall Lights > Wall Lights': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Table & Floor Lamps > Table lamps': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > Table & Floor Lamps > Floor lamps': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > Outdoor Lighting > Outdoor Wall Lighting': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Outdoor Lighting > Landscape Lighting': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Outdoor Hanging Lights': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Outdoor Lighting > Post lighting': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Furniture > Living Room Furniture > End & Side Tables': ('Furniture > Tables > Accent Tables', 4205),
    'Furniture > Living Room Furniture > Coffee Tables': ('Furniture > Tables > Coffee Tables', 4267),
    'Furniture > Living Room Furniture > Accent Chairs': ('Furniture > Chairs', 436),
    'Furniture > Living Room Furniture > TV Stands': ('Furniture > Entertainment Centers & TV Stands', 6391),
    'Furniture > Living Room Furniture > Sofas': ('Furniture > Sofas', 460),
    'Furniture > Living Room Furniture > Sectionals': ('Furniture > Sofas', 460),
    'Furniture > Bedroom Furniture > Nightstands': ('Furniture > Tables > Accent Tables', 4205),
    'Furniture > Bedroom Furniture > Vanity Stools': ('Furniture > Chairs', 436),
    'Furniture > Bedroom Furniture > Beds': ('Furniture > Beds & Accessories > Beds', 451),
    'Furniture > Bedroom Furniture > Dressers': ('Furniture > Cabinets & Storage > Dressers', 6539),
    'Furniture > Office Furniture > Office Chairs': ('Furniture > Chairs > Office Chairs', 503),
    'Furniture > Office Furniture > Desks': ('Furniture > Office Furniture > Desks', 6362),
    'Furniture > Kitchen & Dining Furniture > Dining Chairs & Benches': ('Furniture > Chairs', 436),
    'Furniture > Kitchen & Dining Furniture > Bar & Counter Stools': ('Furniture > Chairs > Bar Stools', 6105),
    'Furniture > Kitchen & Dining Furniture > Dining Tables': ('Furniture > Tables > Kitchen & Dining Room Tables', 6356),
    'Lighting > Outdoor Lighting > Outdoor Post Lights': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Outdoor Lanterns & Lamps': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > Outdoor Lighting > Outdoor Column Light': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Outdoor Ceiling Lights': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Outdoor Lighting > Outdoor Floor lamps': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > Outdoor Lighting > Street Lighting': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Step & Deck Lights': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Spot Lights': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Solar Outdoor Lighting': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > Tree Lighting': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Outdoor Lighting > String Lights': ('Home & Garden > Lighting > Light Strings', 5926),
    'Lighting > Outdoor Lighting > Bollard Lights': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Wall Lights > LED Wall Lights': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Wall Lights > Bathroom Vanity Lighting': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Wall Lights > Swing Arm Wall Sconces': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Wall Lights > Picture Lights': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Wall Lights > Electric Fireplace Lights': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Lighting > Ceiling lights > Directional & Spot Lights': ('Home & Garden > Lighting > Light Fixtures', 594),
    'Lighting > Ceiling lights > Staircase Chandeliers': ('Home & Garden > Lighting > Light Fixtures > Chandeliers', 3247),
    'Lighting > Ceiling lights': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Lighting > Ceiling Fans > Kids Ceiling Fans': ('Home & Garden > Household Appliances > Climate Control Appliances > Air Conditioners > Ceiling Fans', 2806),
    'Lighting > Table & Floor Lamps > Desk lamps': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > Table & Floor Lamps > Baby & Kids Lamp': ('Home & Garden > Lighting > Lamps', 4171),
    'Lighting > String Lights > Outdoor String Lights': ('Home & Garden > Lighting > Light Strings', 5926),
    'Lighting > String Lights > Solar String Lights': ('Home & Garden > Lighting > Light Strings', 5926),
    'Furniture > Office Furniture > Bookcases': ('Furniture > Cabinets & Storage > Bookcases & Standing Shelves', 4099),
    'Furniture > Office Furniture > Gaming Desks': ('Furniture > Office Furniture > Desks', 6362),
    'Furniture > Office Furniture > Conference Tables': ('Furniture > Tables', 6913),
    'Furniture > Kitchen & Dining Furniture > Display Cabinets': ('Furniture > Cabinets & Storage > China Cabinets & Hutches', 6534),
    'Furniture > Kitchen & Dining Furniture > Bar Tables': ('Furniture > Tables > Kitchen & Dining Room Tables', 6356),
    'Furniture > Kitchen & Dining Furniture > Wine Cabinets': ('Furniture > Cabinets & Storage', 6356),
    'Furniture > Kitchen & Dining Furniture > Buffets & Sideboards': ('Furniture > Cabinets & Storage > Sideboards & Buffets', 4148),
    'Furniture > Kitchen & Dining Furniture > Bar & Counter Stool': ('Furniture > Chairs > Bar Stools', 6105),
    'Furniture > Kitchen & Dining Furniture > Dining Table': ('Furniture > Tables > Kitchen & Dining Room Tables', 6356),
    'Furniture > Kitchen & Dining Furniture > Dining Carts': ('Furniture > Cabinets & Storage > Kitchen Islands & Carts', 6386),
    'Furniture > Entryway Furniture > Shoe  Storage': ('Furniture > Cabinets & Storage > Shoe Cabinets', 6539),
    'Furniture > Entryway Furniture > Shoe Benches': ('Furniture > Benches', 6385),
    'Furniture > Entryway Furniture > Hall Trees & Coat Racks': ('Furniture > Cabinets & Storage > Coat Stands', 4083),
    'Furniture > Entryway Furniture > Console Tables': ('Furniture > Tables > Sofa Tables', 6452),
    'Furniture > Living Room Furniture > Low Stools': ('Furniture > Chairs > Ottomans', 442),
    'Furniture > Living Room Furniture > Footstools': ('Furniture > Chairs > Ottomans', 442),
    'Furniture > Living Room Furniture > Recliner': ('Furniture > Chairs', 436),
    'Furniture > Living Room Furniture > Rocking Chairs': ('Furniture > Chairs', 436),
    'Furniture > Living Room Furniture > Cabinets': ('Furniture > Cabinets & Storage', 6356),
    'Furniture > Living Room Furniture > Coffee Table': ('Furniture > Tables > Coffee Tables', 4267),
    'Furniture > Bedroom Furniture > Makeup Vanities': ('Furniture > Beds & Accessories > Bed & Bed Frame Accessories', 5546),
    'Furniture > Bedroom Furniture > Side Tables': ('Furniture > Tables > Accent Tables', 4205),
    'Furniture > Bedroom Furniture > Sofas': ('Furniture > Sofas', 460),
    'Furniture > Outdoor Furniture > Tables': ('Furniture > Outdoor Furniture > Outdoor Tables', 6864),
    'Furniture > Outdoor Furniture > Chairs': ('Furniture > Outdoor Furniture > Outdoor Seating > Outdoor Chairs', 4408),
    'Furniture > Dining Room Furniture > Sofas': ('Furniture > Sofas', 460),
    'Pendant Light': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'Wall Lights': ('Home & Garden > Lighting > Light Fixtures > Wall Light Fixtures', 6071),
    'Chandelier': ('Home & Garden > Lighting > Light Fixtures > Chandeliers', 3247),
    'Night Light': ('Home & Garden > Lighting > Lamps', 4171),
    'Ceiling Fan Light': ('Home & Garden > Lighting > Light Fixtures > Ceiling Light Fixtures', 2956),
    'post light': ('Home & Garden > Lighting > Light Fixtures', 594),
    'String Light': ('Home & Garden > Lighting > Light Strings', 5926),
    'Candlestick': ('Home & Garden > Decor > Candle Holders', 588),
    'Chair': ('Furniture > Chairs', 436),
    '-F1 plant stand h': ('Home & Garden > Lawn & Garden > Gardening > Plant Stands', 721),
    '-F1 plant stand l': ('Home & Garden > Lawn & Garden > Gardening > Plant Stands', 721),
    'F1 plant stand select': ('Home & Garden > Lawn & Garden > Gardening > Plant Stands', 721),
    '-F1 plant stand select': ('Home & Garden > Lawn & Garden > Gardening > Plant Stands', 721),
    'F1 chaise lounge pool': ('Furniture > Outdoor Furniture > Outdoor Seating > Outdoor Chaise Lounges', 4407),
    'F1 bookcase select': ('Furniture > Cabinets & Storage > Bookcases & Standing Shelves', 4099),
    'F tv stands select': ('Furniture > Entertainment Centers & TV Stands', 6391),
    'F1 dining table 251126': ('Furniture > Tables > Kitchen & Dining Room Tables', 6356),
    'Out F': ('Furniture > Outdoor Furniture', 6862),
    'Out No Profit F': ('Furniture > Outdoor Furniture', 6862),
    'N/A': ('Home & Garden', 632),
}


def gpc(custom_cat: str):
    if custom_cat in GPC_MAP:
        return GPC_MAP[custom_cat]
    if custom_cat and custom_cat.startswith("Lighting"):
        return ("Home & Garden > Lighting > Light Fixtures", 594)
    if custom_cat and custom_cat.startswith("Furniture"):
        return ("Furniture", 436)
    return ("Home & Garden", 632)
