<script>
(function(){
  if (window.__lighom_engagement_v2_setup) return;
    window.__lighom_engagement_v2_setup = true;
  var BOT_RE = /fbexternalhit|facebookcatalog|FacebookExternalAgent|meta-externalagent|meta-externalfetcher|facebookbot|pinterestbot|googlebot|bingbot|crawler|spider|HeadlessChrome|headless|phantom|puppeteer|playwright|gptbot|chatgpt|claudebot|anthropic|perplexity|bytespider|amazonbot/i;
  if (BOT_RE.test(navigator.userAgent || "") || navigator.webdriver === true) return;
        function ck(name) { var m = document.cookie.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]+)')); return m ? decodeURIComponent(m[1]) : ''; }
        function eid(prefix){ return prefix + '_' + Date.now() + '_' + Math.random().toString(36).substr(2,9); }
          function ssGet(k){ try { return sessionStorage.getItem(k); } catch(e){ return null; } }
            function ssSet(k,v){ try { sessionStorage.setItem(k,v); } catch(e){} }
              function pushDL(payload){ window.dataLayer = window.dataLayer || []; payload.fbp = ck('_fbp'); payload.fbc = ck('_fbc'); payload.epik = ck('_epik'); window.dataLayer.push(payload); }
                function getProductValue(){
                    try {
                          var s = document.querySelector('variant-radios script[type="application/json"]');
                                if (s) {
                                        var variants = JSON.parse(s.textContent);
                                                var first = variants && variants[0];
                                                        if (first && typeof first.price === 'number') return first.price / 100;
                                                              }
                                                                  } catch(e){}
                                                                      var priceEls = document.querySelectorAll('[class*="price"]');
                                                                          for (var i = 0; i < priceEls.length; i++) {
                                                                                var t = priceEls[i].textContent || '';
                                                                                      var m = t.match(/\$([\d,]+\.\d{2})/);
                                                                                            if (m) return parseFloat(m[1].replace(/,/g, ''));
                                                                                                }
                                                                                                    return 0;
                                                                                                      }
                                                                                                        function pageKey(){ return location.pathname + location.search; }
                                                                                                          // === DeepEngagement composite (scroll>=75 AND time>=60s) ===
                                                                                                            var maxScroll = 0;
                                                                                                              var startTime = Date.now();
                                                                                                                var deepFired = false;
                                                                                                                  function checkDeep(){
                                                                                                                      if (deepFired) return;
                                                                                                                          var docH = document.documentElement.scrollHeight - window.innerHeight;
                                                                                                                              if (docH > 0) {
                                                                                                                                    var pct = Math.min(100, Math.round((window.scrollY || window.pageYOffset || 0) / docH * 100));
                                                                                                                                          if (pct > maxScroll) maxScroll = pct;
                                                                                                                                              }
                                                                                                                                                  var timeOn = Math.round((Date.now() - startTime) / 1000);
                                                                                                                                                      if (maxScroll >= 75 && timeOn >= 60) {
                                                                                                                                                            if (!/^\/products\//.test(location.pathname)) { deepFired = true; return; }
                                                                                                                                                            var key = '__lighom_de_' + location.pathname;
                                                                                                                                                                  try { if (sessionStorage.getItem(key)) { deepFired = true; return; } } catch(e){}
                                                                                                                                                                        deepFired = true; try { sessionStorage.setItem(key, String(Date.now())); } catch(e){}
                                                                                                                                                                              var value = getProductValue();
                                                                                                                                                                                    var eventId = eid('deep');
                                                                                                                                                                                          pushDL({
                                                                                                                                                                                                  event: 'deep_engagement',
                                                                                                                                                                                                          event_id: eventId,
                                                                                                                                                                                                                  engagement_type: 'high',
                                                                                                                                                                                                                          scroll_pct: maxScroll,
                                                                                                                                                                                                                                  time_on_page: timeOn,
                                                                                                                                                                                                                                          value: value,
                                                                                                                                                                                                                                                  currency: 'USD'
                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                              if (window.fbq) {
                                                                                                                                                                                                                                                                      var params = { eventID: eventId };
                                                                                                                                                                                                                                                                              if (value > 0) { params.value = value; params.currency = 'USD'; }
                                                                                                                                                                                                                                                                                      window.fbq('trackCustom', 'DeepEngagement', params, { eventID: eventId });
        /* Browser-side GA4 event with shared event_id for dedup with Worker MP path.
           Benefits from gtag('set','user_data') Enhanced Conversions to Google Ads. */
        if (typeof window.gtag === 'function') {
          try { window.gtag('event', 'deep_engagement', {
            event_id: eventId,
            page_path: location.pathname,
            page_title: document.title,
            engagement_time_msec: 60000,
            scroll_threshold: 75
          }); } catch(e){}
        }
      /* Server-side relay → Worker /capi/event → Meta + Pinterest + GA4 + BQ */
      try {
        var ck2 = function(name){ var m = document.cookie.match(new RegExp('(?:^|;\\s*)' + name + '=([^;]+)')); return m ? decodeURIComponent(m[1]) : ''; };
        fetch('https://lighom-feed-server.dikecarmem750.workers.dev/capi/event', {
          method: 'POST', credentials: 'omit', keepalive: true,
          headers: {'Content-Type':'application/json'},
          body: JSON.stringify({
            event_name: 'DeepEngagement',
            event_id: eventId,
            page_url: location.href, page_path: location.pathname,
            page_type: /\/products\//.test(location.pathname) ? 'product' : (/\/collections\/|\/categories\//.test(location.pathname) ? 'category' : 'other'),
            /* Browser gtag('event','deep_engagement') already fires GA4 with shared event_id — skip Worker GA4 MP. */
            fanout: ['meta', 'pinterest'],
            user_data: (function(){
              var hashed = window.__lighom_user_data_hashed || {};
              var rawG = window.__lighom_user_data_raw || {};
              var out = {
                fbc: ck2('_fbc'), fbp: ck2('_fbp'),
                epik: ck2('_epik'), ttclid: ck2('_ttp'), msclkid: ck2('_uetmsclkid'),
                client_ua: navigator.userAgent, ga_cookie: ck2('_ga')
              };
              ['em','ph','fn','ln','ct','st','zp','country','external_id'].forEach(function(k){
                if (hashed[k]) out[k] = hashed[k];
                else if (rawG[k]) out[k] = rawG[k];
              });
              /* race-fix: external_id from cookie when in-mem cache not yet populated */
              if (!out.external_id) {
                var hEid = ck2('_lighom_user_external_id_h');
                if (hEid && /^[a-f0-9]{64}$/i.test(hEid)) out.external_id = hEid;
                else { var rawEid = ck2('_lighom_user_external_id'); if (rawEid) out.external_id = rawEid; }
              }
              return out;
            })(),
            custom_data: { content_type: 'engagement', engagement_signal: (params && params.engagement_signal) || '' },
            utm: {
              source: ck2('last_utm_source') || ck2('first_utm_source'),
              medium: ck2('last_utm_medium') || ck2('first_utm_medium'),
              campaign: ck2('last_utm_campaign') || ck2('first_utm_campaign')
            }
          })
        }).catch(function(){});
      } catch(e){}
                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                    var sT = null;
                                                                                                                                                                                                                                                                                                      window.addEventListener('scroll', function(){ if (sT) return; sT = setTimeout(function(){ sT = null; checkDeep(); }, 500); }, { passive: true });
                                                                                                                                                                                                                                                                                                        setInterval(checkDeep, 5000);
                                                                                                                                                                                                                                                                                                          // === Cart items cache ===
                                                                                                                                                                                                                                                                                                            if (!window.__lighom_cart_cache_setup) {
                                                                                                                                                                                                                                                                                                                window.__lighom_cart_cache_setup = true;
                                                                                                                                                                                                                                                                                                                    window.dataLayer = window.dataLayer || [];
                                                                                                                                                                                                                                                                                                                        var origPush = window.dataLayer.push;
                                                                                                                                                                                                                                                                                                                            window.dataLayer.push = function(){
                                                                                                                                                                                                                                                                                                                                  try {
                                                                                                                                                                                                                                                                                                                                          for (var i = 0; i < arguments.length; i++) {
                                                                                                                                                                                                                                                                                                                                                    var item = arguments[i];
                                                                                                                                                                                                                                                                                                                                                              if (!item || typeof item !== 'object') continue;
                                                                                                                                                                                                                                                                                                                                                                        var isATC = (item.event === 'add_to_cart') || (item['1'] === 'add_to_cart');
                                                                                                                                                                                                                                                                                                                                                                                  var isPurch = (item.event === 'purchase') || (item['1'] === 'purchase');
                                                                                                                                                                                                                                                                                                                                                                                            if (isATC) {
                                                                                                                                                                                                                                                                                                                                                                                                        var p = item['2'] || item.ecommerce || item;
                                                                                                                                                                                                                                                                                                                                                                                                                    var items = p && p.items;
                                                                                                                                                                                                                                                                                                                                                                                                                                if (items && Array.isArray(items)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                              var existing = [];
                                                                                                                                                                                                                                                                                                                                                                                                                                                            try { existing = JSON.parse(sessionStorage.getItem('lighom_cart_items') || '[]'); } catch(e){}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          items.forEach(function(it){ if (it && (it.item_id || it.id)) existing.push(JSON.parse(JSON.stringify(it))); });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try { sessionStorage.setItem('lighom_cart_items', JSON.stringify(existing.slice(-50))); } catch(e){}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (isPurch) { try { sessionStorage.removeItem('lighom_cart_items'); } catch(e){} }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      } catch(e){}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return origPush.apply(this, arguments);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // === Contact event (replaces phone/email click, deduped per session) ===
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      document.addEventListener('click', function(e){
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var a = e.target.closest && e.target.closest('a');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (!a || !a.href) return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  var href = a.href;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var isPhone = href.indexOf('tel:') === 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          var isMail = href.indexOf('mailto:') === 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (isPhone || isMail) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (ssGet('lighom_contact_fired') === '1') return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ssSet('lighom_contact_fired', '1');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                var contactType = isPhone ? 'phone' : 'email';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      var contactValue = href.replace(/^(tel:|mailto:)/, '').split('?')[0];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            var eventId = eid('contact');
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  pushDL({
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          event: 'contact',
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  event_id: eventId,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          contact_type: contactType,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  contact_value: contactValue
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              if (window.fbq) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      window.fbq('track', 'Contact', { eventID: eventId }, { eventID: eventId });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          if (/^https?:/.test(href)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                try {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        var u = new URL(href);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (u.hostname && u.hostname !== window.location.hostname) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          pushDL({ event: 'outbound_click', event_id: eid('outb'), outbound_url: href.slice(0,200), outbound_host: u.hostname });
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        } catch(e){}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }, true);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              })();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </script>